defmodule Whatsmeow.Keys do
  @moduledoc """
  High-level key-management primitives: X25519 identity keypairs, signed
  pre-keys, ephemeral key generation, and serialisation helpers used by
  both the Noise handshake and the Signal protocol.

  Ports `whatsmeow-main/util/keys/keypair.go` semantics.
  """

  alias Whatsmeow.Crypto.Curve25519

  defmodule KeyPair do
    @moduledoc "An X25519 keypair: 32-byte public + 32-byte private."
    @enforce_keys [:public, :private]
    defstruct [:public, :private]

    @type t :: %__MODULE__{
            public: <<_::256>>,
            private: <<_::256>>
          }
  end

  defmodule PreKey do
    @moduledoc """
    A Signal one-time pre-key: an X25519 keypair plus an ID. Signed pre-keys
    additionally carry a signature over the public key, generated by the
    owner's identity key.
    """
    @enforce_keys [:id, :key_pair]
    defstruct [:id, :key_pair, :signature]

    @type t :: %__MODULE__{
            id: pos_integer(),
            key_pair: KeyPair.t(),
            signature: binary() | nil
          }
  end

  @doc "Generate a fresh keypair."
  @spec generate_keypair() :: KeyPair.t()
  def generate_keypair do
    {pub, priv} = Curve25519.generate_keypair()
    %KeyPair{public: pub, private: priv}
  end

  @doc "Reconstruct a keypair from its private scalar."
  @spec keypair_from_private(binary()) :: KeyPair.t()
  def keypair_from_private(private) when byte_size(private) == 32 do
    %KeyPair{public: Curve25519.public_for(private), private: private}
  end

  @doc """
  Generate a pre-key with the given ID. Returns a `PreKey.t()` with no
  signature.
  """
  @spec generate_pre_key(pos_integer()) :: PreKey.t()
  def generate_pre_key(id) when is_integer(id) and id > 0 do
    %PreKey{id: id, key_pair: generate_keypair()}
  end

  @doc """
  Generate a signed pre-key. The `identity` keypair is used to sign the
  pre-key's public component using XEdDSA-equivalent over the identity
  private key (Signal-style).
  """
  @spec generate_signed_pre_key(KeyPair.t(), pos_integer()) :: PreKey.t()
  def generate_signed_pre_key(%KeyPair{} = identity, id) when is_integer(id) and id > 0 do
    pre_key = generate_pre_key(id)
    signature = sign(identity.private, pre_key.key_pair.public)
    %PreKey{pre_key | signature: signature}
  end

  @doc """
  Sign a 32-byte payload using Signal's XEdDSA-on-Curve25519 convention.

  This implementation is a stub that returns a deterministic HMAC for now;
  the real XEdDSA signing arrives in Phase 7 alongside the Signal protocol
  port. Cryptographically correct verification will be added then.
  """
  @spec sign(<<_::256>>, binary()) :: binary()
  def sign(private, payload) when byte_size(private) == 32 and is_binary(payload) do
    # Phase 7 will replace this with XEdDSA. Until then we emit a HMAC so the
    # signed-prekey record has the expected shape (64 bytes).
    :crypto.mac(:hmac, :sha512, private, payload)
  end
end
