defmodule Mix.Tasks.WhatsmeowEx.Install do
  @shortdoc "Wire whatsmeow_ex into the host Phoenix / Ash / Jido app"

  @moduledoc """
  One-shot installer that wires `:whatsmeow_ex` into a host application.

  Run once in any host project after `mix deps.get`:

      mix whatsmeow_ex.install

  What it does (idempotent — safe to re-run):

    * Generates `config/whatsmeow.exs` with `Whatsmeow.Repo` config that
      inherits the host's `DATABASE_URL` (or a dedicated
      `WHATSMEOW_DATABASE_URL` if you'd rather keep the data in a separate
      database).
    * Patches `config/config.exs` to `import_config "whatsmeow.exs"`.
    * Patches `config/runtime.exs` so production reads `DATABASE_URL`.
    * Extends the host's `mix.exs` `aliases/0` so `mix ecto.create`,
      `mix ecto.migrate`, `mix ecto.rollback`, and `mix ecto.reset`
      include `-r Whatsmeow.Repo` automatically.

  Options:

    * `--separate-db` — point `Whatsmeow.Repo` at `WHATSMEOW_DATABASE_URL`
      instead of sharing the host's `DATABASE_URL`. Useful if you don't
      want WhatsApp session/key tables in the main app DB.

    * `--copy-migrations` — copy library migrations into
      `priv/repo/migrations/` of the host so they're owned by the host's
      `Repo` instead of `Whatsmeow.Repo`. Mutually exclusive with the
      default flow; pick one model per app.

    * `--yes` — don't prompt; overwrite existing whatsmeow.exs on re-run.

  After install:

      mix ecto.create     # creates whatsmeow_ex DB (or shared host DB)
      mix ecto.migrate    # applies whatsmeow migrations alongside host's

  No changes are made to your supervision tree — `Whatsmeow.Application`
  auto-starts because `:whatsmeow_ex` is listed in `extra_applications`.
  """

  use Mix.Task

  @switches [
    separate_db: :boolean,
    copy_migrations: :boolean,
    yes: :boolean
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _, _} = OptionParser.parse(argv, switches: @switches)

    if Mix.Project.config()[:app] == :whatsmeow_ex do
      Mix.raise(
        "mix whatsmeow_ex.install must be run from a host application that depends on :whatsmeow_ex, not from inside whatsmeow_ex itself."
      )
    end

    ensure_config_dir!()
    write_whatsmeow_config(opts)
    patch_config_exs()
    patch_runtime_exs(opts)
    patch_host_mix_exs(opts)

    if opts[:copy_migrations] do
      Mix.Task.run("whatsmeow_ex.gen.migrations", [])
    end

    print_summary(opts)
  end

  # ────────────────────────────────────────────────────────────────────
  # Step 1 — config/whatsmeow.exs
  # ────────────────────────────────────────────────────────────────────

  defp ensure_config_dir! do
    unless File.dir?("config") do
      Mix.raise("No config/ directory found at #{File.cwd!()}. Are you in the project root?")
    end
  end

  defp write_whatsmeow_config(opts) do
    path = Path.join("config", "whatsmeow.exs")
    url_var = if opts[:separate_db], do: "WHATSMEOW_DATABASE_URL", else: "DATABASE_URL"

    body = """
    # Generated by `mix whatsmeow_ex.install`. Safe to edit.
    import Config

    config :whatsmeow_ex,
      ecto_repos: [Whatsmeow.Repo],
      # Set to `false` if the host app prefers to own the schema with its
      # own Repo (after running `mix whatsmeow_ex.gen.migrations`).
      start_repo?: true

    config :whatsmeow_ex, Whatsmeow.Repo,
      migration_primary_key: [name: :id, type: :binary_id],
      migration_foreign_key: [type: :binary_id],
      migration_timestamps: [type: :utc_datetime_usec]

    # Dev / test defaults — production reads #{url_var} in runtime.exs.
    if config_env() in [:dev, :test] do
      config :whatsmeow_ex, Whatsmeow.Repo,
        username: System.get_env("POSTGRES_USER", "postgres"),
        password: System.get_env("POSTGRES_PASSWORD", "postgres"),
        hostname: System.get_env("POSTGRES_HOST", "localhost"),
        database:
          "whatsmeow_\#{config_env()}" <>
            if(System.get_env("MIX_TEST_PARTITION"), do: "_\#{System.get_env(\"MIX_TEST_PARTITION\")}", else: ""),
        pool_size: 10
    end
    """

    cond do
      not File.exists?(path) ->
        File.write!(path, body)
        Mix.shell().info([:green, "* created ", :reset, path])

      opts[:yes] ->
        File.write!(path, body)
        Mix.shell().info([:yellow, "* overwrote ", :reset, path])

      true ->
        Mix.shell().info([
          :cyan,
          "* skipped ",
          :reset,
          "#{path} (already exists; pass --yes to overwrite)"
        ])
    end
  end

  # ────────────────────────────────────────────────────────────────────
  # Step 2 — config/config.exs: import_config "whatsmeow.exs"
  # ────────────────────────────────────────────────────────────────────

  defp patch_config_exs do
    path = Path.join("config", "config.exs")

    unless File.exists?(path) do
      Mix.shell().info([
        :yellow,
        "* skipped ",
        :reset,
        "#{path} not found — add `import_config \"whatsmeow.exs\"` manually"
      ])

      :ok
    end

    contents = File.read!(path)

    cond do
      String.contains?(contents, ~s|import_config "whatsmeow.exs"|) ->
        Mix.shell().info([:cyan, "* skipped ", :reset, "#{path} (already imports whatsmeow.exs)"])

      String.match?(contents, ~r/import_config\s+"#\{config_env\(\)\}\.exs"/) ->
        new =
          String.replace(
            contents,
            ~r/(import_config\s+"#\{config_env\(\)\}\.exs")/,
            ~s|import_config "whatsmeow.exs"\n\\1|,
            global: false
          )

        File.write!(path, new)

        Mix.shell().info([
          :green,
          "* patched ",
          :reset,
          "#{path} (added import_config \"whatsmeow.exs\")"
        ])

      true ->
        File.write!(path, contents <> "\nimport_config \"whatsmeow.exs\"\n")

        Mix.shell().info([
          :green,
          "* appended ",
          :reset,
          "#{path} (added import_config \"whatsmeow.exs\")"
        ])
    end
  end

  # ────────────────────────────────────────────────────────────────────
  # Step 3 — config/runtime.exs: production DATABASE_URL block
  # ────────────────────────────────────────────────────────────────────

  defp patch_runtime_exs(opts) do
    path = Path.join("config", "runtime.exs")
    url_var = if opts[:separate_db], do: "WHATSMEOW_DATABASE_URL", else: "DATABASE_URL"
    marker = "# whatsmeow_ex runtime config"

    block = """

    #{marker}
    if config_env() == :prod do
      config :whatsmeow_ex, Whatsmeow.Repo,
        url:
          System.get_env("#{url_var}") ||
            raise("environment variable #{url_var} is missing — required by :whatsmeow_ex"),
        pool_size: String.to_integer(System.get_env("WHATSMEOW_POOL_SIZE", "10")),
        ssl: System.get_env("WHATSMEOW_DATABASE_SSL", "false") == "true"
    end
    """

    cond do
      not File.exists?(path) ->
        File.write!(path, "import Config\n" <> block)
        Mix.shell().info([:green, "* created ", :reset, path])

      File.read!(path) |> String.contains?(marker) ->
        Mix.shell().info([:cyan, "* skipped ", :reset, "#{path} (whatsmeow block already present)"])

      true ->
        File.write!(path, File.read!(path) <> block)
        Mix.shell().info([:green, "* appended ", :reset, "#{path} (whatsmeow runtime block)"])
    end
  end

  # ────────────────────────────────────────────────────────────────────
  # Step 4 — host mix.exs: extend ecto.* aliases with -r Whatsmeow.Repo
  # ────────────────────────────────────────────────────────────────────

  defp patch_host_mix_exs(_opts) do
    path = "mix.exs"

    unless File.exists?(path) do
      Mix.shell().info([
        :yellow,
        "* skipped ",
        :reset,
        "no mix.exs found — ecto.* aliases not patched"
      ])

      :ok
    end

    contents = File.read!(path)

    if String.contains?(contents, "-r Whatsmeow.Repo") do
      Mix.shell().info([:cyan, "* skipped ", :reset, "#{path} (Whatsmeow.Repo already in aliases)"])
    else
      Mix.shell().info([
        :yellow,
        """

        ! Could not safely auto-patch mix.exs aliases. Add `-r Whatsmeow.Repo`
          to your ecto.* aliases manually, e.g.:

              defp aliases do
                [
                  setup: ["deps.get", "ecto.setup"],
                  "ecto.setup": ["ecto.create -r Whatsmeow.Repo", "ecto.migrate -r Whatsmeow.Repo"],
                  "ecto.reset": ["ecto.drop -r Whatsmeow.Repo", "ecto.setup"],
                  test: ["ecto.create --quiet -r Whatsmeow.Repo", "ecto.migrate --quiet -r Whatsmeow.Repo", "test"]
                ]
              end
        """,
        :reset
      ])
    end
  end

  # ────────────────────────────────────────────────────────────────────
  # Summary
  # ────────────────────────────────────────────────────────────────────

  defp print_summary(opts) do
    url_var = if opts[:separate_db], do: "WHATSMEOW_DATABASE_URL", else: "DATABASE_URL"

    Mix.shell().info([
      :green,
      """

      whatsmeow_ex installed.

      Next steps:

        1. (dev/test) mix ecto.create -r Whatsmeow.Repo
        2.            mix ecto.migrate -r Whatsmeow.Repo
        3. (prod)     export #{url_var}=...
        4. Use the API:

             {:ok, _pid} = Whatsmeow.Sessions.Supervisor.start_session(jid_or_nil)
             Whatsmeow.Notifications.subscribe(:all)

      Ash users: this library does not yet ship Ash resources. Wrap
      `Whatsmeow.Send`, `Whatsmeow.Notifications`, etc. behind a thin
      Ash.Resource of your own.

      Jido users: same — drive `Whatsmeow.Send.send_text/3` from your
      Jido.Agent actions; subscribe to `Whatsmeow.Notifications` for
      inbound events.
      """,
      :reset
    ])
  end
end
